name: Publish Docker image

on:
  push:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: username/repository-name
          tags: raspi

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64
      - run: git clone -b rec-4.8.4 https://github.com/PowerDNS/pdns.git


      - run: git clone https://github.com/PowerDNS/pdns-builder.git pdns/builder
    #   - run: ./builder/build.sh debian-bookworm-arm64
      - run:  docker buildx build -f Dockerfile-recursor -t pdns-recursor:raspi .
        working-directory: pdns
      - run:  docker buildx build -f Dockerfile-dnsdist -t dnsdist:raspi .
        working-directory: pdns
      - run:  docker buildx build -f Dockerfile-auth -t pdns-auth:raspi .
        working-directory: pdns
