name: Build Docker image

on:
  push:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image:
          - recursor
          - dnsdist
          - auth
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: username/repository-name
          tags: raspi

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Colne pdns
        run: git clone -b rec-4.8.4 https://github.com/PowerDNS/pdns.git

      - name: Colne pdns-builder
        run: git clone https://github.com/PowerDNS/pdns-builder.git pdns/builder

      - run: cp Dockerfile-auth pdns/Dockerfile-auth

      - run: >-
          docker buildx build
          -f Dockerfile-${{ matrix.docker_image }}
          -t pdns-${{ matrix.docker_image }}:rec-4.8.4
          --platform linux/arm64
          -o type=docker,dest=- . > pdns-${{ matrix.docker_image }}.tar
        working-directory: pdns
      - run: docker images
      - run: ls -ls pdns/pdns-${{ matrix.docker_image }}.tar

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: pdns-${{ matrix.docker_image }}
          path: pdns/pdns-${{ matrix.docker_image }}.tar
          retention-days: 1
